/**
 * Asset registry — imports from Supabase Storage 'cheeky-assets' bucket.
 *
 * Use this module instead of local imports for all app assets (icons,
 * brand images, persona graphics, coat check personas, floor cards, audio).
 *
 * Usage:
 *   import { assetUrl, assetManifest } from '@/utils/assets';
 *   <img src={assetUrl('icons', 'chat_bubble.webp')} />
 *   <img src={ASSETS.icons.chatBubble} />
 *
 * The manifest is generated by scripts/upload-assets.mjs and written to
 * public/asset-manifest.json. It maps every uploaded file to its Supabase
 * Storage URL.
 */

import manifest from '@/utils/asset-manifest.json';

export type AssetCategory =
  | 'icons'
  | 'brand'
  | 'personas'
  | 'coat-check'
  | 'floors'
  | 'audio'
  | 'misc';

export interface AssetEntry {
  slug: string;
  category: string;
  filename: string;
  url: string;
  sizeBytes: number;
  mimeType: string;
}

/** Base URL for the cheeky-assets bucket */
export const ASSETS_BASE_URL = manifest.baseUrl;

/** Full asset manifest (all uploaded files) */
export const assetManifest: AssetEntry[] = manifest.assets;

/**
 * Get the public URL for an asset by category and filename.
 * Falls back to a constructed URL if the manifest doesn't have it
 * (e.g. for assets uploaded after the manifest was generated).
 */
export function assetUrl(category: string, filename: string): string {
  const entry = manifest.assets.find(
    (a: AssetEntry) => a.category === category && a.filename === filename
  );
  if (entry) return entry.url;
  // Fallback: construct the URL from the pattern
  return `${ASSETS_BASE_URL}/${category}/${filename}`;
}

/**
 * Get all assets in a category.
 */
export function assetsByCategory(category: string): AssetEntry[] {
  return manifest.assets.filter((a: AssetEntry) => a.category === category);
}

/**
 * Find an asset by its slug.
 */
export function assetBySlug(slug: string): AssetEntry | undefined {
  return manifest.assets.find((a: AssetEntry) => a.slug === slug);
}

/**
 * Get the URL for a persona image by character slug and variant.
 * Personas are stored under the 'personas' category with subdirectories.
 */
export function personaUrl(
  characterSlug: string,
  variant: string = 'portrait'
): string {
  return `${ASSETS_BASE_URL}/personas/${characterSlug}/${variant}.webp`;
}

/**
 * Get the URL for a coat check persona by variant slug.
 */
export function coatCheckPersonaUrl(variantSlug: string): string {
  return `${ASSETS_BASE_URL}/coat-check/${variantSlug}.webp`;
}

/**
 * Get the URL for a floor card image.
 */
export function floorCardUrl(tier: string): string {
  return `${ASSETS_BASE_URL}/floors/card-${tier}.webp`;
}

/**
 * Get the URL for a floor background image.
 */
export function floorBgUrl(tier: string): string {
  return `${ASSETS_BASE_URL}/floors/${tier}.webp`;
}

/**
 * Get the URL for a brand image.
 */
export function brandUrl(name: string): string {
  return `${ASSETS_BASE_URL}/brand/${name}.webp`;
}

/**
 * Get the URL for an icon by filename (with or without extension).
 */
export function iconUrl(name: string): string {
  const filename = name.endsWith('.webp') ? name : `${name}.webp`;
  return assetUrl('icons', filename);
}

// ── Convenience constants for commonly-used assets ──────────────
// These are typed so you can import and use them directly:
//   <img src={ASSETS.icons.chatBubble} />
//   <img src={ASSETS.brand.entrance} />

export const ASSETS = {
  icons: {
    chatBubble: iconUrl('chat_bubble'),
    cheekyChats: iconUrl('cheeky_chats'),
    coatCheck: iconUrl('coat_check'),
    danceFloor: iconUrl('dance_floor'),
    diamond: iconUrl('diamond'),
    diamondBadge: iconUrl('diamond_badge'),
    diamondFloor: iconUrl('diamond_floor'),
    drink: iconUrl('drink'),
    enterClub: iconUrl('enter_club'),
    eventCenter: iconUrl('event_center'),
    firstChat: iconUrl('first_chat'),
    firstDate: iconUrl('first_date'),
    gift: iconUrl('gift'),
    giftShop: iconUrl('gfift_shop'),
    goldBadge: iconUrl('gold_badge'),
    goldFloor: iconUrl('gold_floor'),
    heart: iconUrl('heart'),
    heartAndKey: iconUrl('heart_and_key'),
    joinNow: iconUrl('join_now'),
    neonHeart: iconUrl('neon_heart'),
    neonHeartSign: iconUrl('neon_heart_sign'),
    platinumBadge: iconUrl('platinum_badge'),
    platinumFloor: iconUrl('platinum_floor'),
    rubyBadge: iconUrl('ruby_badge'),
    sapphireBadge: iconUrl('sapphire_badge'),
    silverBadge: iconUrl('silver_badge'),
    silverFloor: iconUrl('silver_floor'),
    sparkList: iconUrl('spark_list'),
    speedDating: iconUrl('speed_dating1'),
    star: iconUrl('star'),
    swagShop: iconUrl('swag_shop'),
    velvetRope: iconUrl('velvet_rope'),
    vipLounge: iconUrl('vip_lounge'),
    wink: iconUrl('wink'),
  },
  brand: {
    entrance: brandUrl('entrance'),
    entranceLogo: brandUrl('entrance-logo'),
    clubInterior: brandUrl('club-interior'),
    floorFree: brandUrl('floor-free'),
    floorGold: brandUrl('floor-gold'),
    floorPlatinum: brandUrl('floor-platinum'),
    floorDiamond: brandUrl('floor-diamond'),
  },
  floors: {
    silver: floorCardUrl('silver'),
    gold: floorCardUrl('gold'),
    platinum: floorCardUrl('platinum'),
    diamond: floorCardUrl('diamond'),
  },
  coatCheck: {
    sashaBlondeThai: coatCheckPersonaUrl('sasha-v2-blonde-thai'),
    sashaTheKeeper: coatCheckPersonaUrl('sasha-the-keeper'),
    sashaBlackHairEdgy: coatCheckPersonaUrl('sasha-v3-black-hair-edgy'),
    jaxDefault: coatCheckPersonaUrl('jax2'),
    jaxVaultkeeper: coatCheckPersonaUrl('jax-the-vaultkeeper'),
    jaxSlickedBack: coatCheckPersonaUrl('jax-v2-slicked-back'),
  },
  personas: {
    brutus: personaUrl('brutus'),
    brutusDoor: personaUrl('brutus', 'door'),
    dj: personaUrl('dj'),
    djStage: personaUrl('dj', 'stage'),
    djCrowd: personaUrl('dj', 'crowd'),
    bartender: personaUrl('bartender'),
    bartenderFullbody: personaUrl('bartender', 'fullbody'),
    trixie: personaUrl('trixie'),
    trixieFullbody: personaUrl('trixie', 'fullbody'),
    hostess: personaUrl('hostess'),
    hostessFullbody: personaUrl('hostess', 'fullbody'),
    chaz: personaUrl('chaz'),
    chazStrut: personaUrl('chaz', 'strut'),
  },
  audio: {
    clubCheeky: `${ASSETS_BASE_URL}/audio/Club_Cheeky.mp3`,
    pressureGauge: `${ASSETS_BASE_URL}/audio/pressure-gauge.mp3`,
    solarFlareSummit: `${ASSETS_BASE_URL}/audio/solar-flare-summit.mp3`,
    aboveTheClouds: `${ASSETS_BASE_URL}/audio/above-the-clouds.mp3`,
    finalAscent: `${ASSETS_BASE_URL}/audio/final-ascent.mp3`,
  },
} as const;
