-- search_path pin pass (generated by scripts/gen-fn-search-path.mjs, 2026-08-08):
-- 6 functions had no search_path and inherited the caller's
-- path (mutable — a consistency risk, and a hijack vector for the SECURITY
-- DEFINER trigger functions). Each now pins `pg_catalog, public`.

-- compatible(a uuid, b uuid)
CREATE OR REPLACE FUNCTION public.compatible(a uuid, b uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE
 SET search_path = pg_catalog, public
AS $function$
  select exists (
    select 1
    from public.profiles pa
    join public.profiles pb on true
    where pa.id = a and pb.id = b
      and pa.gender is not null and pb.gender is not null
      and pa.interested_in in ('everyone', case pb.gender when 'lady' then 'women' else 'men' end)
      and pb.interested_in in ('everyone', case pa.gender when 'lady' then 'women' else 'men' end)
  );
$function$
;

-- current_tier(p_user uuid)
CREATE OR REPLACE FUNCTION public.current_tier(p_user uuid)
 RETURNS text
 LANGUAGE plpgsql
 STABLE
 SET search_path = pg_catalog, public
AS $function$
declare
  v_tier text;
begin
  -- Guest pass first (most recent, unexpired).
  select tier into v_tier
  from public.guest_passes
  where guest_id = p_user and expires_at > now()
  order by created_at desc
  limit 1;
  if v_tier is not null then
    return v_tier;
  end if;

  -- Complimentary grant.
  select tier into v_tier
  from public.entitlement_grants
  where user_id = p_user and expires_at > now()
  order by created_at desc
  limit 1;
  if v_tier is not null then
    return v_tier;
  end if;

  -- Paid subscription.
  select coalesce(p.name, 'Standard Membership') into v_tier
  from public.subscriptions s
  join public.prices pr on pr.id = s.price_id
  join public.products p on p.id = pr.product_id
  where s.user_id = p_user
    and s.status in ('active', 'trialing')
  order by s.created_at desc
  limit 1;

  return case v_tier
    when 'Gold Membership' then 'gold'
    when 'Platinum Membership' then 'platinum'
    when 'Diamond Club' then 'diamond'
    else 'standard'
  end;
end;
$function$
;

-- handle_new_profile()
CREATE OR REPLACE FUNCTION public.handle_new_profile()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path = pg_catalog, public
AS $function$
begin
  insert into public.profiles (id, gender, interested_in)
  values (new.id,
          nullif(new.raw_user_meta_data->>'gender', ''),
          coalesce(nullif(new.raw_user_meta_data->>'interested_in', ''), 'everyone'));
  insert into public.profile_private (id, birthday)
  values (new.id, nullif(new.raw_user_meta_data->>'birthday', '')::date);
  return new;
end;
$function$
;

-- handle_new_user()
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path = pg_catalog, public
AS $function$
begin
  insert into public.users (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$function$
;

-- set_updated_at()
CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path = pg_catalog, public
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;

-- tier_rank(p_tier text)
CREATE OR REPLACE FUNCTION public.tier_rank(p_tier text)
 RETURNS integer
 LANGUAGE sql
 IMMUTABLE
 SET search_path = pg_catalog, public
AS $function$
  select case p_tier
    when 'diamond' then 3
    when 'platinum' then 2
    when 'gold' then 1
    else 0
  end;
$function$
;

