-- Revoke member (authenticated) execute from service-role-only SECURITY
-- DEFINER functions (generated by scripts/gen-revoke-member.mjs, 2026-08-08).
-- Supabase default privileges grant EXECUTE to authenticated on every new
-- function — so after revoking anon, a logged-in member could still call
-- owner_grant (grant themselves a tier) or generate_swag_code (mint codes).
-- These run only via the service role (owner booth, webhook, AI path,
-- internal/cron) and now require it. Member-facing RPCs are untouched.

revoke execute on function public.advance_blind_date(p_event_id uuid) from authenticated;
revoke execute on function public.auto_match_rooftop(p_event_id uuid) from authenticated;
revoke execute on function public.award_badge(p_user uuid, p_slug text) from authenticated;
revoke execute on function public.award_gem(p_user uuid, p_slug text) from authenticated;
revoke execute on function public.enforce_photo_limit() from authenticated;
revoke execute on function public.ensure_events(p_hours integer) from authenticated;
revoke execute on function public.ensure_speed_dating_events(p_hours integer) from authenticated;
revoke execute on function public.finalize_events() from authenticated;
revoke execute on function public.flag_honeypot_catch(p_field text, p_page text, p_email text, p_user uuid) from authenticated;
revoke execute on function public.flag_honeypot_catch(p_user uuid, p_field text, p_page text, p_email text) from authenticated;
revoke execute on function public.flag_swag_request(p_user uuid, p_actor_ref text, p_benefit_type text, p_benefit_value text, p_reason text) from authenticated;
revoke execute on function public.generate_swag_code(p_benefit_type text, p_benefit_value text, p_actor_type text, p_actor_ref text, p_expires_at timestamp with time zone, p_max_uses integer, p_notes text) from authenticated;
revoke execute on function public.handle_bot_guard() from authenticated;
revoke execute on function public.handle_first_event_badge() from authenticated;
revoke execute on function public.handle_first_match_moment() from authenticated;
revoke execute on function public.handle_new_profile() from authenticated;
revoke execute on function public.handle_new_user() from authenticated;
revoke execute on function public.mark_webhook_processed(p_event_id text, p_event_type text, p_payload jsonb) from authenticated;
revoke execute on function public.next_event_minutes(p_kind text) from authenticated;
revoke execute on function public.owner_grant(p_user uuid, p_benefit_type text, p_benefit_value text, p_reason text, p_days integer) from authenticated;
revoke execute on function public.record_character_moment(p_user uuid, p_character_slug text, p_milestone text, p_message text) from authenticated;
revoke execute on function public.record_common_moment(p_user uuid, p_milestone text) from authenticated;
revoke execute on function public.record_personal_moment(p_user uuid, p_milestone text) from authenticated;
revoke execute on function public.setup_speed_dating(p_event_id uuid) from authenticated;
revoke execute on function public.tick_rooftop_events() from authenticated;
