-- RLS perf pass (generated by scripts/gen-rls-wrap.mjs, 2026-08-08):
-- 49 policies called auth.uid()/auth.jwt()/auth.role()/current_setting()
-- directly in their quals, forcing per-row evaluation. Each call is now
-- wrapped in a scalar subquery `(select ...)` so it computes once per
-- statement. Semantics unchanged — the functions never depend on row values.

-- benefit_grants: Read your own swag history
drop policy if exists "Read your own swag history" on public."benefit_grants";
create policy "Read your own swag history" on public."benefit_grants"
  as permissive
  for select
  using ((user_id = (select auth.uid())))
;

-- blind_date_answers: Blind date answers: host reads all, suitors read their own
drop policy if exists "Blind date answers: host reads all, suitors read their own" on public."blind_date_answers";
create policy "Blind date answers: host reads all, suitors read their own" on public."blind_date_answers"
  as permissive
  for select
  using (((user_id = (select auth.uid())) OR (EXISTS ( SELECT 1
   FROM (blind_date_rounds r
     JOIN events e ON ((e.id = r.event_id)))
  WHERE ((r.id = blind_date_answers.round_id) AND (e.host_id = (select auth.uid())))))))
;

-- blocks: Block someone
drop policy if exists "Block someone" on public."blocks";
create policy "Block someone" on public."blocks"
  as permissive
  for insert
  with check ((blocker_id = (select auth.uid())))
;

-- blocks: Read your blocks
drop policy if exists "Read your blocks" on public."blocks";
create policy "Read your blocks" on public."blocks"
  as permissive
  for select
  using ((blocker_id = (select auth.uid())))
;

-- certificates: Read your certificates
drop policy if exists "Read your certificates" on public."certificates";
create policy "Read your certificates" on public."certificates"
  as permissive
  for select
  using ((user_id = (select auth.uid())))
;

-- character_moments: Mark your moments seen
drop policy if exists "Mark your moments seen" on public."character_moments";
create policy "Mark your moments seen" on public."character_moments"
  as permissive
  for update
  using ((user_id = (select auth.uid())))
  with check ((user_id = (select auth.uid())))
;

-- character_moments: Read your moments
drop policy if exists "Read your moments" on public."character_moments";
create policy "Read your moments" on public."character_moments"
  as permissive
  for select
  using ((user_id = (select auth.uid())))
;

-- character_relations: Insert your character relations
drop policy if exists "Insert your character relations" on public."character_relations";
create policy "Insert your character relations" on public."character_relations"
  as permissive
  for insert
  with check ((user_id = (select auth.uid())))
;

-- character_relations: Read your character relations
drop policy if exists "Read your character relations" on public."character_relations";
create policy "Read your character relations" on public."character_relations"
  as permissive
  for select
  using ((user_id = (select auth.uid())))
;

-- consents: Users read their own consents
drop policy if exists "Users read their own consents" on public."consents";
create policy "Users read their own consents" on public."consents"
  as permissive
  for select
  using (((select auth.uid()) = user_id))
;

-- consents: Users record their own consents
drop policy if exists "Users record their own consents" on public."consents";
create policy "Users record their own consents" on public."consents"
  as permissive
  for insert
  with check (((select auth.uid()) = user_id))
;

-- conversations: Read your conversations
drop policy if exists "Read your conversations" on public."conversations";
create policy "Read your conversations" on public."conversations"
  as permissive
  for select
  using (((user_id_a = (select auth.uid())) OR (user_id_b = (select auth.uid()))))
;

-- daily_checkins: Read your check-ins
drop policy if exists "Read your check-ins" on public."daily_checkins";
create policy "Read your check-ins" on public."daily_checkins"
  as permissive
  for select
  using ((user_id = (select auth.uid())))
;

-- date_night_picks: Read your own picks
drop policy if exists "Read your own picks" on public."date_night_picks";
create policy "Read your own picks" on public."date_night_picks"
  as permissive
  for select
  using ((user_id = (select auth.uid())))
;

-- date_nights: Date nights are visible to the couple
drop policy if exists "Date nights are visible to the couple" on public."date_nights";
create policy "Date nights are visible to the couple" on public."date_nights"
  as permissive
  for select
  using (((user_a = (select auth.uid())) OR (user_b = (select auth.uid()))))
;

-- date_rooms: Date rooms are visible to the pair
drop policy if exists "Date rooms are visible to the pair" on public."date_rooms";
create policy "Date rooms are visible to the pair" on public."date_rooms"
  as permissive
  for select
  using (((user_a = (select auth.uid())) OR (user_b = (select auth.uid()))))
;

-- entitlement_grants: Read your own grants
drop policy if exists "Read your own grants" on public."entitlement_grants";
create policy "Read your own grants" on public."entitlement_grants"
  as permissive
  for select
  using ((user_id = (select auth.uid())))
;

-- event_picks: Read your own picks
drop policy if exists "Read your own picks" on public."event_picks";
create policy "Read your own picks" on public."event_picks"
  as permissive
  for select
  using ((picker_id = (select auth.uid())))
;

-- gift_inventory: Read your inventory
drop policy if exists "Read your inventory" on public."gift_inventory";
create policy "Read your inventory" on public."gift_inventory"
  as permissive
  for select
  using ((user_id = (select auth.uid())))
;

-- gift_sends: Gift sends are private to the two parties
drop policy if exists "Gift sends are private to the two parties" on public."gift_sends";
create policy "Gift sends are private to the two parties" on public."gift_sends"
  as permissive
  for select
  using (((sender_id = (select auth.uid())) OR (recipient_id = (select auth.uid()))))
;

-- guest_passes: Guest reads passes they hold
drop policy if exists "Guest reads passes they hold" on public."guest_passes";
create policy "Guest reads passes they hold" on public."guest_passes"
  as permissive
  for select
  using ((guest_id = (select auth.uid())))
;

-- guest_passes: Host reads passes they sent
drop policy if exists "Host reads passes they sent" on public."guest_passes";
create policy "Host reads passes they sent" on public."guest_passes"
  as permissive
  for select
  using ((host_id = (select auth.uid())))
;

-- l3_picks: Read your own L3 picks
drop policy if exists "Read your own L3 picks" on public."l3_picks";
create policy "Read your own L3 picks" on public."l3_picks"
  as permissive
  for select
  using (((picker_id = (select auth.uid())) OR (target_id = (select auth.uid()))))
;

-- l3_rewards: Read your own L3 rewards
drop policy if exists "Read your own L3 rewards" on public."l3_rewards";
create policy "Read your own L3 rewards" on public."l3_rewards"
  as permissive
  for select
  using ((user_id = (select auth.uid())))
;

-- likes: Read likes you sent or received
drop policy if exists "Read likes you sent or received" on public."likes";
create policy "Read likes you sent or received" on public."likes"
  as permissive
  for select
  using (((liker_id = (select auth.uid())) OR (likee_id = (select auth.uid()))))
;

-- matches: Read matches you are part of
drop policy if exists "Read matches you are part of" on public."matches";
create policy "Read matches you are part of" on public."matches"
  as permissive
  for select
  using (((user_id_a = (select auth.uid())) OR (user_id_b = (select auth.uid()))))
;

-- member_badges: Read your badges
drop policy if exists "Read your badges" on public."member_badges";
create policy "Read your badges" on public."member_badges"
  as permissive
  for select
  using ((user_id = (select auth.uid())))
;

-- member_gems: Read your gems
drop policy if exists "Read your gems" on public."member_gems";
create policy "Read your gems" on public."member_gems"
  as permissive
  for select
  using ((user_id = (select auth.uid())))
;

-- messages: Read messages in your conversations
drop policy if exists "Read messages in your conversations" on public."messages";
create policy "Read messages in your conversations" on public."messages"
  as permissive
  for select
  using ((EXISTS ( SELECT 1
   FROM conversations c
  WHERE ((c.id = messages.conversation_id) AND ((c.user_id_a = (select auth.uid())) OR (c.user_id_b = (select auth.uid())))))))
;

-- miss_streaks: Read your own streak
drop policy if exists "Read your own streak" on public."miss_streaks";
create policy "Read your own streak" on public."miss_streaks"
  as permissive
  for select
  using ((user_id = (select auth.uid())))
;

-- photos: Users add their own photos
drop policy if exists "Users add their own photos" on public."photos";
create policy "Users add their own photos" on public."photos"
  as permissive
  for insert
  with check (((select auth.uid()) = user_id))
;

-- photos: Users delete their own photos
drop policy if exists "Users delete their own photos" on public."photos";
create policy "Users delete their own photos" on public."photos"
  as permissive
  for delete
  using (((select auth.uid()) = user_id))
;

-- photos: Users update their own photos
drop policy if exists "Users update their own photos" on public."photos";
create policy "Users update their own photos" on public."photos"
  as permissive
  for update
  using (((select auth.uid()) = user_id))
;

-- profile_private: Users read their own private profile
drop policy if exists "Users read their own private profile" on public."profile_private";
create policy "Users read their own private profile" on public."profile_private"
  as permissive
  for select
  using (((select auth.uid()) = id))
;

-- profile_private: Users update their own private profile
drop policy if exists "Users update their own private profile" on public."profile_private";
create policy "Users update their own private profile" on public."profile_private"
  as permissive
  for update
  using (((select auth.uid()) = id))
;

-- profiles: Users create their own profile
drop policy if exists "Users create their own profile" on public."profiles";
create policy "Users create their own profile" on public."profiles"
  as permissive
  for insert
  with check (((select auth.uid()) = id))
;

-- profiles: Users update their own profile
drop policy if exists "Users update their own profile" on public."profiles";
create policy "Users update their own profile" on public."profiles"
  as permissive
  for update
  using (((select auth.uid()) = id))
;

-- reports: File a report
drop policy if exists "File a report" on public."reports";
create policy "File a report" on public."reports"
  as permissive
  for insert
  with check ((reporter_id = (select auth.uid())))
;

-- rooftop_picks: Rooftop picks: read your own
drop policy if exists "Rooftop picks: read your own" on public."rooftop_picks";
create policy "Rooftop picks: read your own" on public."rooftop_picks"
  as permissive
  for select
  using ((picker_id = (select auth.uid())))
;

-- special_interests: Add your interests
drop policy if exists "Add your interests" on public."special_interests";
create policy "Add your interests" on public."special_interests"
  as permissive
  for insert
  with check ((user_id = (select auth.uid())))
;

-- special_interests: Read your interests
drop policy if exists "Read your interests" on public."special_interests";
create policy "Read your interests" on public."special_interests"
  as permissive
  for select
  using ((user_id = (select auth.uid())))
;

-- speed_selections: Read your selections
drop policy if exists "Read your selections" on public."speed_selections";
create policy "Read your selections" on public."speed_selections"
  as permissive
  for select
  using ((user_id = (select auth.uid())))
;

-- speed_session_messages: Read session chat for your group
drop policy if exists "Read session chat for your group" on public."speed_session_messages";
create policy "Read session chat for your group" on public."speed_session_messages"
  as permissive
  for select
  using ((EXISTS ( SELECT 1
   FROM speed_sessions s
  WHERE ((s.event_id = speed_session_messages.event_id) AND (s.group_number = speed_session_messages.group_number) AND ((s.user_a = (select auth.uid())) OR (s.user_b = (select auth.uid())))))))
;

-- subscriptions: Can only view own subs data.
drop policy if exists "Can only view own subs data." on public."subscriptions";
create policy "Can only view own subs data." on public."subscriptions"
  as permissive
  for select
  using (((select auth.uid()) = user_id))
;

-- token_ledger: Users read their own token ledger
drop policy if exists "Users read their own token ledger" on public."token_ledger";
create policy "Users read their own token ledger" on public."token_ledger"
  as permissive
  for select
  using (((select auth.uid()) = user_id))
;

-- users: Can update own user data.
drop policy if exists "Can update own user data." on public."users";
create policy "Can update own user data." on public."users"
  as permissive
  for update
  using (((select auth.uid()) = id))
;

-- users: Can view own user data.
drop policy if exists "Can view own user data." on public."users";
create policy "Can view own user data." on public."users"
  as permissive
  for select
  using (((select auth.uid()) = id))
;

-- waves: Send a wave
drop policy if exists "Send a wave" on public."waves";
create policy "Send a wave" on public."waves"
  as permissive
  for insert
  with check ((sender_id = (select auth.uid())))
;

-- waves: Waves are visible to the two parties
drop policy if exists "Waves are visible to the two parties" on public."waves";
create policy "Waves are visible to the two parties" on public."waves"
  as permissive
  for select
  using (((sender_id = (select auth.uid())) OR (recipient_id = (select auth.uid()))))
;

