-- Revoke anon/PUBLIC execute on security-definer RPCs (generated by
-- scripts/gen-revoke-definer.mjs, 2026-08-08): 62 functions were
-- callable without signing in (Postgres's default PUBLIC EXECUTE grant).
-- anon and PUBLIC lose execute; authenticated (where granted) and
-- service_role keep it, so the app, the owner, and the webhook paths are
-- unaffected and members keep every RPC the UI calls.

revoke execute on function public.add_special_interest(p_interest_user uuid) from anon, public;
revoke execute on function public.advance_blind_date(p_event_id uuid) from anon, public;
revoke execute on function public.auto_match_rooftop(p_event_id uuid) from anon, public;
revoke execute on function public.award_badge(p_user uuid, p_slug text) from anon, public;
revoke execute on function public.award_gem(p_user uuid, p_slug text) from anon, public;
revoke execute on function public.bump_rate_limit(p_key text, p_window_seconds integer, p_max integer) from anon, public;
revoke execute on function public.buy_gift(p_slug text) from anon, public;
revoke execute on function public.create_blind_date() from anon, public;
revoke execute on function public.create_l3_pick(p_target uuid, p_choice text) from anon, public;
revoke execute on function public.create_like(p_likee uuid) from anon, public;
revoke execute on function public.current_streak() from anon, public;
revoke execute on function public.date_night_leaderboard(p_pack uuid) from anon, public;
revoke execute on function public.date_night_state(p_game uuid) from anon, public;
revoke execute on function public.enforce_photo_limit() from anon, public;
revoke execute on function public.ensure_events(p_hours integer) from anon, public;
revoke execute on function public.ensure_floor_events(p_hours integer) from anon, public;
revoke execute on function public.ensure_speed_dating_events(p_hours integer) from anon, public;
revoke execute on function public.finalize_events() from anon, public;
revoke execute on function public.flag_honeypot_catch(p_field text, p_page text, p_email text, p_user uuid) from anon, public;
revoke execute on function public.flag_honeypot_catch(p_user uuid, p_field text, p_page text, p_email text) from anon, public;
revoke execute on function public.flag_swag_request(p_user uuid, p_actor_ref text, p_benefit_type text, p_benefit_value text, p_reason text) from anon, public;
revoke execute on function public.generate_swag_code(p_benefit_type text, p_benefit_value text, p_actor_type text, p_actor_ref text, p_expires_at timestamp with time zone, p_max_uses integer, p_notes text) from anon, public;
revoke execute on function public.get_or_create_conversation(p_other uuid) from anon, public;
revoke execute on function public.handle_bot_guard() from anon, public;
revoke execute on function public.handle_first_event_badge() from anon, public;
revoke execute on function public.handle_first_match_moment() from anon, public;
revoke execute on function public.handle_new_profile() from anon, public;
revoke execute on function public.handle_new_user() from anon, public;
revoke execute on function public.is_test_member() from anon, public;
revoke execute on function public.join_blind_date(p_event_id uuid) from anon, public;
revoke execute on function public.join_event(p_event_id uuid) from anon, public;
revoke execute on function public.l3_trio() from anon, public;
revoke execute on function public.leave_blind_date(p_event_id uuid) from anon, public;
revoke execute on function public.leave_event(p_event_id uuid) from anon, public;
revoke execute on function public.mark_conversation_read(p_conversation_id uuid) from anon, public;
revoke execute on function public.mark_webhook_processed(p_event_id text, p_event_type text, p_payload jsonb) from anon, public;
revoke execute on function public.next_event_minutes(p_kind text) from anon, public;
revoke execute on function public.owner_grant(p_user uuid, p_benefit_type text, p_benefit_value text, p_reason text, p_days integer) from anon, public;
revoke execute on function public.pick_on_floor(p_event_id uuid, p_pickee uuid) from anon, public;
revoke execute on function public.record_character_moment(p_user uuid, p_character_slug text, p_milestone text, p_message text) from anon, public;
revoke execute on function public.record_checkin() from anon, public;
revoke execute on function public.record_common_moment(p_user uuid, p_milestone text) from anon, public;
revoke execute on function public.record_personal_moment(p_user uuid, p_milestone text) from anon, public;
revoke execute on function public.redeem_swag_code(p_code text) from anon, public;
revoke execute on function public.resolve_song(p_match_id uuid, p_continue boolean) from anon, public;
revoke execute on function public.resolve_speed_dating(p_event_id uuid) from anon, public;
revoke execute on function public.respond_gift(p_send_id uuid, p_accept boolean) from anon, public;
revoke execute on function public.select_blind_tally(p_event_id uuid, p_round integer, p_selected uuid) from anon, public;
revoke execute on function public.select_speed_rank(p_event_id uuid, p_pick_rank smallint, p_picked uuid) from anon, public;
revoke execute on function public.send_event_message(p_conversation_id uuid, p_body text) from anon, public;
revoke execute on function public.send_gift(p_gift_id uuid, p_recipient uuid) from anon, public;
revoke execute on function public.send_guest_pass(p_guest uuid) from anon, public;
revoke execute on function public.send_message(p_conversation_id uuid, p_body text) from anon, public;
revoke execute on function public.send_speed_message(p_event_id uuid, p_group integer, p_slot integer, p_body text) from anon, public;
revoke execute on function public.setup_speed_dating(p_event_id uuid) from anon, public;
revoke execute on function public.start_date_night(p_other uuid) from anon, public;
revoke execute on function public.submit_blind_answer(p_event_id uuid, p_round integer, p_body text) from anon, public;
revoke execute on function public.submit_blind_question(p_event_id uuid, p_round integer, p_question text) from anon, public;
revoke execute on function public.submit_rooftop_pick(p_event_id uuid, p_round integer, p_pickee uuid) from anon, public;
revoke execute on function public.tap_date_night(p_game uuid, p_index integer, p_pick smallint) from anon, public;
revoke execute on function public.taskbar_state() from anon, public;
revoke execute on function public.tick_rooftop_events() from anon, public;

-- Club Chat functions — revoke anon/public, keep authenticated grants
revoke execute on function public.club_chat_send(text, text) from anon, public;
revoke execute on function public.club_chat_horn(text) from anon, public;
revoke execute on function public.club_chat_whisper_get(uuid) from anon, public;
revoke execute on function public.club_chat_whisper_send(uuid, text) from anon, public;
revoke execute on function public.club_chat_invite(uuid) from anon, public;
revoke execute on function public.club_chat_respond_invite(uuid, boolean) from anon, public;
revoke execute on function public.club_chat_heartbeat(int) from anon, public;
revoke execute on function public.club_chat_bump_badges(uuid) from anon, public;
revoke execute on function public.bump_rate_limit(text, int, int) from anon, public;
